// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _5I_Frisoni_Differenze.Migrations
{
    [DbContext(typeof(DbTrovaLeDifferenze))]
    [Migration("20220417101102_CreazioneDB")]
    partial class CreazioneDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Differenza", b =>
                {
                    b.Property<int>("idDifferenza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DomandaImmagineID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Raggio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("idDifferenza");

                    b.HasIndex("DomandaImmagineID");

                    b.ToTable("Differenze");
                });

            modelBuilder.Entity("DomandaImmagine", b =>
                {
                    b.Property<int>("DomandaImmagineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PercorsoModificata")
                        .HasColumnType("TEXT");

                    b.Property<string>("PercorsoOriginale")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("DomandaImmagineID");

                    b.ToTable("DomandeImmagine");
                });

            modelBuilder.Entity("Differenza", b =>
                {
                    b.HasOne("DomandaImmagine", "DomandaImmagine")
                        .WithMany("Differenze")
                        .HasForeignKey("DomandaImmagineID");

                    b.Navigation("DomandaImmagine");
                });

            modelBuilder.Entity("DomandaImmagine", b =>
                {
                    b.Navigation("Differenze");
                });
#pragma warning restore 612, 618
        }
    }
}
